-- Migration: add-all-incidents-types
-- Created at: 2021-04-20 16:32:11
-- ====  UP  ====
INSERT INTO `incidentTypes`(`name`) values
  ('PARCEL_MISSING_PRODUCT'),
  ('PARCEL_NEVER_RECEIVED'),
  ('PARCEL_PROOF_OF_DELIVERY'),
  ('PARCEL_RECEIVED_DAMAGED'),
  ('RECIPIENT_RETURN_MISSING_PRODUCT'),
  ('RECIPIENT_RETURN_NEVER_RECEIVED'),
  ('RECIPIENT_RETURN_PROOF_OF_DELIVERY'),
  ('RECIPIENT_RETURN_RECEIVED_DAMAGED');
-- ==== DOWN ====
DELETE FROM `incidentTypes`
WHERE `name` in
  ('PARCEL_MISSING_PRODUCT'),
  ('PARCEL_NEVER_RECEIVED'),
  ('PARCEL_PROOF_OF_DELIVERY'),
  ('PARCEL_RECEIVED_DAMAGED'),
  ('RECIPIENT_RETURN_MISSING_PRODUCT'),
  ('RECIPIENT_RETURN_NEVER_RECEIVED'),
  ('RECIPIENT_RETURN_PROOF_OF_DELIVERY'),
  ('RECIPIENT_RETURN_RECEIVED_DAMAGED');
