const INCIDENT_TYPES = {
  PARCEL_LATE_DELIVERY: 'PARCEL_LATE_DELIVERY',
  PARCEL_MISSING_PRODUCT: 'PARCEL_MISSING_PRODUCT',
  PARCEL_NEVER_RECEIVED: 'PARCEL_NEVER_RECEIVED',
  PARCEL_PROOF_OF_DELIVERY: 'PARCEL_PROOF_OF_DELIVERY',
  PARCEL_RECEIVED_DAMAGED: 'PARCEL_RECEIVED_DAMAGED',
  PRODUCT_DAMAGED_IN_WAREHOUSE: 'PRODUCT_DAMAGED_IN_WAREHOUSE',
  PRODUCT_LOST_IN_WAREHOUSE: 'PRODUCT_LOST_IN_WAREHOUSE',
  RECIPIENT_RETURN_MISSING_PRODUCT: 'RECIPIENT_RETURN_MISSING_PRODUCT',
  RECIPIENT_RETURN_NEVER_RECEIVED: 'RECIPIENT_RETURN_NEVER_RECEIVED',
  RECIPIENT_RETURN_PROOF_OF_DELIVERY: 'RECIPIENT_RETURN_PROOF_OF_DELIVERY',
  RECIPIENT_RETURN_RECEIVED_DAMAGED: 'RECIPIENT_RETURN_RECEIVED_DAMAGED',
  CONSUMER_RETURN: 'CONSUMER_RETURN',
  ATTACHMENT_FAILED_UPLOAD: 'ATTACHMENT_FAILED_UPlOAD'
};

module.exports = { INCIDENT_TYPES };
