const TICKET_TYPES = {
  ORDER: 'ORDER',
  RETURN_ORDER: 'RETURN_ORDER',
  WIO: 'WIO',
  INVOICE: 'INVOICE',
  SKU: 'SKU'
};
const TYPES = {
  SHIPPER_GENERAL: 'SHIPPER_GENERAL_DATA',
  GENERAL: 'GENERAL_DATA',
  ...TICKET_TYPES
};

const TICKET_REASON_TYPES = {
  INVOICE_ERROR: 'INVOICE_ERROR',
  INVOICE_OTHER: 'INVOICE_OTHER',
  INVOICE_PAYMENT_PROOF: 'INVOICE_PAYMENT_PROOF',
  PARCEL_MISSING_PRODUCT: 'PARCEL_MISSING_PRODUCT',
  PARCEL_NEVER_RECEIVED: 'PARCEL_NEVER_RECEIVED',
  PARCEL_OTHER: 'PARCEL_OTHER',
  PARCEL_PROOF_OF_DELIVERY: 'PARCEL_PROOF_OF_DELIVERY',
  PARCEL_RECEIVED_DAMAGED: 'PARCEL_RECEIVED_DAMAGED',
  PARCEL_LATE_DELIVERY: 'PARCEL_LATE_DELIVERY',
  CONSUMER_RETURN: 'CONSUMER_RETURN',
  RECIPIENT_RETURN_MISSING_PRODUCT: 'RECIPIENT_RETURN_MISSING_PRODUCT',
  RECIPIENT_RETURN_NEVER_RECEIVED: 'RECIPIENT_RETURN_NEVER_RECEIVED',
  RECIPIENT_RETURN_OTHER: 'RECIPIENT_RETURN_OTHER',
  RECIPIENT_RETURN_PROOF_OF_DELIVERY: 'RECIPIENT_RETURN_PROOF_OF_DELIVERY',
  RECIPIENT_RETURN_RECEIVED_DAMAGED: 'RECIPIENT_RETURN_RECEIVED_DAMAGED',
  PRODUCT_DAMAGED_IN_WAREHOUSE: 'PRODUCT_DAMAGED_IN_WAREHOUSE',
  SKU_INVENTORY_GAP: 'SKU_INVENTORY_GAP',
  PRODUCT_LOST_IN_WAREHOUSE: 'PRODUCT_LOST_IN_WAREHOUSE',
  SKU_OTHER: 'SKU_OTHER',
  WIO_INBOUND_GAP: 'WIO_INBOUND_GAP',
  WIO_OTHER: 'WIO_OTHER'
};

const PARCEL_EVENT_TYPES = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  CANCELLED: 'CANCELLED',
  ASSOCIATED: 'ASSOCIATED',
  DISSOCIATED: 'DISSOCIATED',
  PREPARED: 'PREPARED',
  UNPREPARED: 'UNPREPARED',
  PICKED: 'PICKED',
  UNPICKED: 'UNPICKED',
  CARRIER_UPDATED: 'CARRIER_UPDATED',
  CARRIER_WEIGHT_UPDATED: 'CARRIER_WEIGHT_UPDATED',
  ATTACHMENT_PRINTED: 'ATTACHMENT_PRINTED',
  RETURN_CREATED: 'RETURN_CREATED',
  RETURN_RECEIVED: 'RETURN_RECEIVED',
  DUPLICATE_CREATED: 'DUPLICATE_CREATED',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  INFO_RECEIVED: 'INFO_RECEIVED',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  FAILED_ATTEMPT: 'FAILED_ATTEMPT',
  DELIVERED: 'DELIVERED',
  EXCEPTION: 'EXCEPTION',
  EXPIRED: 'EXPIRED',
  PENDING: 'PENDING',
  DELETED: 'DELETED',
  WEIGHED: 'WEIGHED',
  SET_ASIDE: 'SET_ASIDE',
  INBOUND_ERROR: 'INBOUND_ERROR',
  INBOUNDED: 'INBOUNDED',
  LABEL_GENERATED: 'LABEL_GENERATED',
  LABEL_GENERATION_FAILED: 'LABEL_GENERATION_FAILED',
  VALIDATED: 'VALIDATED',
  FREEZED: 'FREEZED',
  UNFREEZED: 'UNFREEZED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESTARTED: 'RESTARTED',
  SIZED: 'SIZED'
};

const ORDER_EVENTS_TYPES = [
  PARCEL_EVENT_TYPES.CREATED,
  PARCEL_EVENT_TYPES.VALIDATED,
  PARCEL_EVENT_TYPES.PICKED,
  PARCEL_EVENT_TYPES.SHIPPED,
  PARCEL_EVENT_TYPES.IN_TRANSIT,
  PARCEL_EVENT_TYPES.OUT_FOR_DELIVERY,
  PARCEL_EVENT_TYPES.FAILED_ATTEMPT,
  PARCEL_EVENT_TYPES.DELIVERED,
  PARCEL_EVENT_TYPES.EXCEPTION,
  PARCEL_EVENT_TYPES.RETURN_RECEIVED,
  PARCEL_EVENT_TYPES.CANCELLED
];

module.exports = {
  TYPES,
  TICKET_TYPES,
  TICKET_REASON_TYPES,
  ORDER_EVENTS_TYPES,
  PARCEL_EVENT_TYPES
};
