require('dotenv').config();
const TrustEnv = require('trust-env').default;

module.exports = TrustEnv([
  { key: 'CAROTTE_AMQP_HOST', type: 'string', required: false, preset: 'rabbitmq:5672' },
  { key: 'CAROTTE_AMQP_PREFETCH', type: 'integer' },
  { key: 'CAROTTE_GRACEFUL_SHUTDOWN_TIMEOUT', type: 'integer' },
  { key: 'CAROTTE_TEARDOWN_AMQP_CLOSE_TIMEOUT', type: 'integer' },
  { key: 'CAROTTE_TEARDOWN_MYSQL_TIMEOUT', type: 'integer' },
  { key: 'CAROTTE_LOADER_LEGACY_MODE', type: 'boolean' },
  { key: 'DB_HOST', type: 'string' },
  { key: 'DB_PASS', type: 'string' },
  { key: 'DB_USER', type: 'string' },
  { key: 'DB_PORT', type: 'integer' },
  { key: 'DB_DATABASE', type: 'string' },
  { key: 'DB_PRODUCT_READ_HOST', type: 'string' },
  { key: 'DB_PRODUCT_READ_PASS', type: 'string' },
  { key: 'DB_PRODUCT_READ_USER', type: 'string' },
  { key: 'DB_PRODUCT_READ_PORT', type: 'integer' },
  { key: 'ZENDESK_EMAIL', type: 'string', required: false },
  { key: 'ZENDESK_PASSWORD', type: 'string', required: false },
  { key: 'ZENDESK_DOMAIN', type: 'string', required: false },
  { key: 'ZENDESK_AUTHOR_ID', type: 'string', required: false },
  { key: 'ZENDESK_API_THROTTLE_COUNT', type: 'integer' },
  { key: 'ZENDESK_API_THROTTLE_SECONDS', type: 'integer' },
  { key: 'ZENDESK_API_CHUNK_DATE_SECONDS', type: 'integer' },
  { key: 'ZENDESK_FIELD_AMOUNT_TO_REFUND', type: 'string' },
  { key: 'ZENDESK_FIELD_CARRIER_TRACKING_ID', type: 'string' },
  { key: 'ZENDESK_FIELD_CUBYN_RESOLUTION', type: 'string' },
  { key: 'ZENDESK_FIELD_CUBYN_STATUS', type: 'string' },
  { key: 'ZENDESK_FIELD_CUBYN_TRACKING_NUMBER', type: 'string' },
  { key: 'ZENDESK_FIELD_INSURANCE', type: 'string' },
  { key: 'ZENDESK_FIELD_INSURANCE_CLAIM', type: 'string' },
  { key: 'ZENDESK_FIELD_RECIPIENT', type: 'string' },
  { key: 'ZENDESK_FIELD_REFUND_ANNOUNCED_DATE', type: 'string' },
  { key: 'ZENDESK_FIELD_REFUND_TO_CREATE', type: 'string' },
  { key: 'ZENDESK_FIELD_REFUND_TYPE', type: 'string' },
  { key: 'ZENDESK_FIELD_REFUND_STATUS', type: 'string' },
  { key: 'ZENDESK_FIELD_REQUEST_TYPE', type: 'string' },
  { key: 'ZENDESK_FIELD_RESPONSIBILITY', type: 'string' },
  { key: 'ZENDESK_FIELD_SHIPPING_FEES_REFUND', type: 'string' },
  { key: 'ZENDESK_FIELD_SHIPPING_PROVIDER', type: 'string' },
  { key: 'ZENDESK_FIELD_SHIPPING_PROVIDER_INQUIRY_NUMBER', type: 'string' },
  { key: 'ZENDESK_FIELD_SHIPPING_PROVIDER_INQUIRY_STATUS', type: 'string' },
  { key: 'ZENDESK_FIELD_TICKET_CREATED_BY', type: 'string' },
  { key: 'TRUSTPILOT_API_BASE_URL', type: 'string' },
  { key: 'TRUSTPILOT_API_KEY', type: 'string', required: false },
  { key: 'TRUSTPILOT_API_SECRET', type: 'string', required: false },
  { key: 'TRUSTPILOT_BUSINESS_UNIT_ID', type: 'string' },
  { key: 'TRUSTPILOT_USERNAME', type: 'string', required: false },
  { key: 'TRUSTPILOT_PASSWORD', type: 'string', required: false },
  { key: 'TRUSTPILOT_INVITATIONS_API_BASE_URL', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_REPLY_TO_EMAIL', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_SENDER_NAME', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_SENDER_EMAIL', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_DEFAULT_LANGUAGE', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_DEFAULT_LOCALE', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_ENGLISH_TEMPLATE_ID', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_FRENCH_TEMPLATE_ID', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_SPANISH_TEMPLATE_ID', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_DEFAULT_TEMPLATE_ID', type: 'string' },
  { key: 'TRUSTPILOT_INVITATION_REDIRECT_URI', type: 'string' },
  { key: 'TRUSTPILOT_TOKENS_HOST_ID', type: 'integer' },
  { key: 'TRUSTPILOT_TODO_DELAY', type: 'integer' },
  { key: 'TRUSTPILOT_FAILED_MAX_RETRIES', type: 'integer' },
  { key: 'TRUSTPILOT_PROCESS_BULK_SIZE', type: 'integer' },
  { key: 'TRUSTPILOT_SHIPPER_BLACKLIST', type: 'string', required: false },
  { key: 'BANK_REFUND_LIST_SEND_TO_FR', type: 'string' },
  { key: 'BANK_REFUND_LIST_SEND_TO_ES', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_NAME', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_FR_CTRY', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_FR_IBAN', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_FR_BIC', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_ES_CTRY', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_ES_IBAN', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_ES_BIC', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_CHARGE_BEARER', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_PAYMENT_METHOD', type: 'string' },
  { key: 'BANK_REFUND_LIST_ORG_SERVICE_LEVEL', type: 'string' }
]);
